# Generated by Django 4.0.4 on 2022-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс после транзакции')),
                ('transaction_type', models.PositiveIntegerField(choices=[(1, 'Пополнение'), (2, 'Вывод'), (3, 'Зачисление на баланс'), (4, 'На удержании')], verbose_name='Тип транзакции')),
                ('detail_pay', models.CharField(blank=True, max_length=250, null=True, verbose_name='Детали платежа')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['timestamp'],
            },
        ),
    ]
