# Generated by Django 4.0.4 on 2022-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Баланс после транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Пополнение'), (2, 'Вывод'), (3, 'Зачисление на баланс'), (4, 'На удержании')], null=True, verbose_name='Тип транзакции'),
        ),
    ]
