# Generated by Django 4.0.4 on 2022-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_balance_after_transaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Пополнение'), (2, 'Вывод'), (3, 'Зачисление на баланс'), (4, 'Покупка')], null=True, verbose_name='Тип транзакции'),
        ),
    ]
