# Generated by Django 4.0.4 on 2022-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Пополнение'), (2, 'Вывод'), (3, 'Зачисление на баланс'), (4, 'Покупка'), (5, 'Продление')], null=True, verbose_name='Тип транзакции'),
        ),
    ]
