# Generated by Django 4.0.4 on 2022-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Отклонено', 'Отклонено'), ('В обработке', 'В обработке')], max_length=100, null=True, verbose_name='Статус заявки'),
        ),
    ]
