# Generated by Django 4.0.4 on 2022-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Отклонено', 'Отклонено'), ('В обработке', 'В обработке'), ('Выполнено', 'Выполнено')], max_length=100, null=True, verbose_name='Статус заявки'),
        ),
    ]
