# Generated by Django 4.0.4 on 2022-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all',
            field=models.BooleanField(default=None, verbose_name='Отправить всем'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo',
            field=models.BooleanField(default=None, verbose_name='Сео специалистам'),
        ),
        migrations.AddField(
            model_name='event',
            name='web',
            field=models.BooleanField(default=None, verbose_name='Вебмастерам'),
        ),
    ]
