# Generated by Django 4.0.4 on 2022-05-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date'], 'verbose_name': 'Подписчик на рассылку', 'verbose_name_plural': 'Подписчики на рассылку'},
        ),
    ]
