# Generated by Django 4.0.4 on 2022-05-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус модерации')),
            ],
            options={
                'verbose_name': 'Статус модерации',
                'verbose_name_plural': 'Статусы модерации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VerifyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус проверки')),
            ],
            options={
                'verbose_name': 'Статус проверки',
                'verbose_name_plural': 'Статусы проверок',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('valid_date', models.DateTimeField(blank=True, verbose_name='В работе до')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('price_per_item', models.IntegerField(default=0, verbose_name='Цена за 1 месяц')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('count_month', models.IntegerField(default=1, verbose_name='Количество месяцев')),
                ('moderation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link_app.moderation', verbose_name='Статус модерации')),
                ('status_verify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link_app.verifystatus', verbose_name='Статус проверки')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('-created',),
            },
        ),
    ]
