# Generated by Django 4.0.4 on 2022-05-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import link_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус модерации')),
            ],
            options={
                'verbose_name': 'Статус модерации',
                'verbose_name_plural': 'Статусы модерации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VerifyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус проверки')),
            ],
            options={
                'verbose_name': 'Статус проверки',
                'verbose_name_plural': 'Статусы проверок',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('valid_date', models.DateTimeField(default=link_app.models.one_week_hence)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('moderation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link_app.moderation', verbose_name='Статус модерации')),
                ('status_verify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link_app.verifystatus', verbose_name='Статус проверки')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.website', verbose_name='url сайта')),
                ('user_email', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email заказчика')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('-created',),
            },
        ),
    ]
