# Generated by Django 4.0.4 on 2022-05-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_app', '0001_initial'),
        ('link_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.website', verbose_name='url сайта'),
        ),
    ]
