# Generated by Django 4.0.4 on 2022-05-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='user_email',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email заказчика'),
        ),
    ]
