# Generated by Django 4.0.4 on 2022-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
