# Generated by Django 4.0.4 on 2022-05-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_initial'),
        ('link_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_url', to='site_app.website', verbose_name='url сайта'),
        ),
    ]
