# Generated by Django 4.0.4 on 2022-05-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0005_alter_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='link',
            name='total_price',
        ),
    ]
