# Generated by Django 4.0.4 on 2022-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0006_remove_link_price_per_item_remove_link_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='moderation',
            field=models.CharField(choices=[('Проверено', 'Проверено'), ('На проверке', 'На проверке'), ('Отображается', 'Отображается')], default='На проверке', max_length=25, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status_verify',
            field=models.CharField(choices=[('Проверено', 'Проверено'), ('На проверке', 'На проверке'), ('Отображается', 'Отображается')], default='На проверке', max_length=25, verbose_name='Статус проверки'),
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
        migrations.DeleteModel(
            name='VerifyStatus',
        ),
    ]
