# Generated by Django 4.0.4 on 2022-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0007_alter_link_moderation_alter_link_status_verify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='moderation',
            field=models.CharField(choices=[('Отклонено', 'Отклонено'), ('На проверке', 'На проверке'), ('Отображается', 'Отображается')], default='На проверке', max_length=25, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status_verify',
            field=models.CharField(choices=[('Отклонено', 'Отклонено'), ('На проверке', 'На проверке'), ('Отображается', 'Отображается')], default='На проверке', max_length=25, verbose_name='Статус проверки'),
        ),
    ]
