# Generated by Django 4.0.4 on 2022-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_app', '0008_alter_link_moderation_alter_link_status_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link2',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка2'),
        ),
    ]
