# Generated by Django 4.0.4 on 2022-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_for_all_time', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Заработано за всё время')),
                ('balance_current', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Заработано на текущий момент')),
                ('balance_hold', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='На удержании')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
        ),
    ]
