# Generated by Django 4.0.4 on 2022-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='password_yandex',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пароль от статистики'),
        ),
        migrations.AlterField(
            model_name='website',
            name='sold_link',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продано ссылок'),
        ),
        migrations.AlterField(
            model_name='website',
            name='total_link',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего ссылок'),
        ),
        migrations.AlterField(
            model_name='website',
            name='yandex_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Яндекс Икс'),
        ),
    ]
