# Generated by Django 4.0.4 on 2022-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('version', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Версия')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Инструкция')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('photo', models.ImageField(blank=True, upload_to='icon_plugins/%Y/%m/%d/', verbose_name='Иконка плагина')),
                ('file', models.FileField(upload_to='plugins/%Y/%m/%d/', verbose_name='Плагин')),
            ],
            options={
                'verbose_name': 'Плагин',
                'verbose_name_plural': 'Плагины',
            },
        ),
    ]
