# Generated by Django 4.0.4 on 2022-06-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
