# Generated by Django 4.0.4 on 2022-05-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_helpcategory_generalhelp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newflatpage',
            options={'verbose_name': 'Содержание страницы', 'verbose_name_plural': 'Содержание страниц'},
        ),
    ]
