# Generated by Django 4.0.4 on 2022-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('text', models.TextField(verbose_name='Ответ на вопрос')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('main', models.BooleanField(default=False, verbose_name='Добавить на главную страницу')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
