# Generated by Django 4.0.4 on 2022-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[('Общие вопросы', 'Общие вопросы'), ('Вебмастерам', 'Вебмастерам'), ('Сео специалистам', 'Сео специалистам')], max_length=50, verbose_name='Категория'),
        ),
    ]
