# Generated by Django 4.0.4 on 2022-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_help_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Статистика'),
            preserve_default=False,
        ),
    ]
