# Generated by Django 4.0.4 on 2022-05-13 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmz', models.CharField(max_length=200, verbose_name='WMZ-кошелёк')),
                ('ymoney', models.CharField(max_length=200, verbose_name='ЮMoney-кошелёк')),
                ('current_balance', models.PositiveIntegerField(default=0, verbose_name='Текущий баланс')),
                ('hold_balance', models.PositiveIntegerField(verbose_name='На удержании')),
                ('output_balance', models.PositiveIntegerField(verbose_name='Ожидает вывода')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
