# Generated by Django 4.0.4 on 2022-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Текущий баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hold_balance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='На удержании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='output_balance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидает вывода'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wmz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='WMZ-кошелёк'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ymoney',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ЮMoney-кошелёк'),
        ),
    ]
