# Generated by Django 4.0.4 on 2022-05-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_name_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hold_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='На удержании'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='output_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ожидает вывода'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
