# Generated by Django 4.0.4 on 2022-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='increase',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Наценка %'),
        ),
    ]
