# Generated by Django 4.0.4 on 2022-06-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_alter_website_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликовано', 'Опубликовано'), ('Отклонено', 'Отклонено')], default='На модерации', max_length=20),
        ),
    ]
